language: ruby
rvm:
  - 2.6.3

git:
  clone: false

env:
  global:
    - GIT_USER="CI BOT"
    - GIT_EMAIL="cibot@test.com"
    - GIT_REPO="lamber-ken"
    - GIT_PROJECT="lamber-ken.github.io"
    - GIT_BRANCH="asf-site"
    - DOCS_ROOT="`pwd`/${GIT_PROJECT}/docs"

before_install:
  - git config --global user.name ${GIT_USER}
  - git config --global user.email ${GIT_EMAIL}
  - git clone https://${GIT_TOKEN}@github.com/${GIT_REPO}/${GIT_PROJECT}.git
  - cd ${GIT_PROJECT} && git checkout ${GIT_BRANCH}
  - gem install bundler:2.0.2

script:
  - pushd ${DOCS_ROOT}
  - bundle install
  - bundle update --bundler
  - bundle exec jekyll build _config.yml --source . --destination _site
  - popd

after_success:
#  - \cp -rf ${DOCS_ROOT}/_site/* content
#  - git add -A
#  - git commit -am "Travis CI build asf-site"
#  - git push origin asf-site
  - mv ${DOCS_ROOT}/_site .
  - rm -rf ${DOCS_ROOT}
  - \cp -rf _site/* .
  - git add -A
  - git commit -am "Travis CI build asf-site"
  - git push origin asf-site:master --force

branches:
  only:
    - asf-site



